package nl.ttva66.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import nl.ttva66.dto.DagDto;
import nl.ttva66.dto.TypeDto;
import nl.ttva66.dto.ZaaldienstDto;
import nl.ttva66.interfaces.DagRequest;
import nl.ttva66.interfaces.ZaalDienstRequest;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01 Sat Aug 10 22:50:37
 * CEST 2013 Generated source version: 2.3.1-patch-01
 * 
 */

@WebService(targetNamespace = "http://www.ttva66.nl/wsdl", name = "Service")
@XmlSeeAlso({ ObjectFactory.class })
public interface Service {

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "login", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.Login")
	@WebMethod
	@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.LoginResponse")
	public ZaaldienstDto login(
			@WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0,
			@WebParam(name = "arg1", targetNamespace = "") java.lang.String arg1);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "saveDag", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.SaveDag")
	@WebMethod
	@ResponseWrapper(localName = "saveDagResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.SaveDagResponse")
	public DagDto saveDag(
			@WebParam(name = "arg0", targetNamespace = "") DagDto arg0);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getDagByDate", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.GetDagByDate")
	@WebMethod
	@ResponseWrapper(localName = "getDagByDateResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.GetDagByDateResponse")
	public DagDto getDagByDate(
			@WebParam(name = "arg0", targetNamespace = "") DagRequest arg0);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "saveZaaldienst", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.SaveZaaldienst")
	@WebMethod
	@ResponseWrapper(localName = "saveZaaldienstResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.SaveZaaldienstResponse")
	public ZaaldienstDto saveZaaldienst(
			@WebParam(name = "arg0", targetNamespace = "") ZaaldienstDto arg0);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "listZaaldiensten", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.ListZaaldiensten")
	@WebMethod
	@ResponseWrapper(localName = "listZaaldienstenResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.ListZaaldienstenResponse")
	public java.util.List<java.lang.Integer> listZaaldiensten();

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "listTypes", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.ListTypes")
	@WebMethod
	@ResponseWrapper(localName = "listTypesResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.ListTypesResponse")
	public java.util.List<TypeDto> listTypes();

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "getZaaldienstById", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.GetZaaldienstById")
	@WebMethod
	@ResponseWrapper(localName = "getZaaldienstByIdResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.GetZaaldienstByIdResponse")
	public ZaaldienstDto getZaaldienstById(
			@WebParam(name = "arg0", targetNamespace = "") ZaalDienstRequest arg0);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "createType", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.CreateType")
	@WebMethod
	@ResponseWrapper(localName = "createTypeResponse", targetNamespace = "http://www.ttva66.nl/wsdl", className = "nl.ttva66.client.CreateTypeResponse")
	public TypeDto createType(
			@WebParam(name = "arg0", targetNamespace = "") TypeDto arg0);
}
