package nl.ttva66.entities;

// Generated 22-jun-2013 16:02:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import javax.persistence.UniqueConstraint;


/**
 * Dag generated by hbm2java
 */
@Entity
@Table(name = "dag", catalog = "ttv", uniqueConstraints = @UniqueConstraint(columnNames = {"dag", "maand", "jaar"}))
public class Dag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String team;
	private String opmerkingen;
	private int dag;
	private int maand;
	private int jaar;
	private Set<Open> opens = new HashSet<Open>(0);
	private Set<Dienst> diensts = new HashSet<Dienst>(0);

	public Dag() {
	}

	public Dag(String team, String opmerkingen, int dag, int maand, int jaar) {
		this.team = team;
		this.opmerkingen = opmerkingen;
		this.dag = dag;
		this.maand = maand;
		this.jaar = jaar;
	}

	public Dag(String team, String opmerkingen, Date datum, int dag, int maand, int jaar, Set<Open> opens,
			Set<Dienst> diensts) {
		this.team = team;
		this.opmerkingen = opmerkingen;
		this.dag = dag;
		this.maand = maand;
		this.jaar = jaar;
		this.opens = opens;
		this.diensts = diensts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "team", nullable = true)
	public String getTeam() {
		return this.team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	@Column(name = "opmerkingen", nullable = true, length = 65535)
	public String getOpmerkingen() {
		return this.opmerkingen;
	}

	public void setOpmerkingen(String opmerkingen) {
		this.opmerkingen = opmerkingen;
	}

	@Column(name = "dag", nullable = false, length = 10)
	public int getDag() {
		return this.dag;
	}

	public void setDag(int dag) {
		this.dag = dag;
	}
	
	@Column(name = "maand", nullable = false, length = 10)
	public int getMaand()
	{
		return maand;
	}
	public void setMaand(int maand)
	{
		this.maand = maand;
	}
	
	@Column(name = "jaar", nullable = false, length = 10)
	public int getJaar()
	{
		return this.jaar;
	}
	public void setJaar(int jaar)
	{
		this.jaar = jaar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dag")
	public Set<Open> getOpens() {
		return this.opens;
	}

	public void setOpens(Set<Open> opens) {
		this.opens = opens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dag")
	public Set<Dienst> getDiensts() {
		return this.diensts;
	}

	public void setDiensts(Set<Dienst> diensts) {
		this.diensts = diensts;
	}

}
