package nl.ttva66.entities;

// Generated 22-jun-2013 16:02:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "ttv")
public class Type implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String naam;
	private int start;
	private int eind;
	private Set<Open> opens = new HashSet<Open>(0);
	private Set<Dienst> diensts = new HashSet<Dienst>(0);

	public Type() {
	}

	public Type(String naam, int start, int eind) {
		this.naam = naam;
		this.start = start;
		this.eind = eind;
	}

	public Type(String naam, int start, int eind, Set<Open> opens,
			Set<Dienst> diensts) {
		this.naam = naam;
		this.start = start;
		this.eind = eind;
		this.opens = opens;
		this.diensts = diensts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "naam", nullable = false)
	public String getNaam() {
		return this.naam;
	}

	public void setNaam(String naam) {
		this.naam = naam;
	}

	@Column(name = "start", nullable = false)
	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	@Column(name = "eind", nullable = false)
	public int getEind() {
		return this.eind;
	}

	public void setEind(int eind) {
		this.eind = eind;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "type")
	public Set<Open> getOpens() {
		return this.opens;
	}

	public void setOpens(Set<Open> opens) {
		this.opens = opens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Dienst> getDiensts() {
		return this.diensts;
	}

	public void setDiensts(Set<Dienst> diensts) {
		this.diensts = diensts;
	}

}
