package nl.ttva66;

// Generated 22-jun-2013 16:02:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Dag generated by hbm2java
 */
@Entity
@Table(name = "dag", catalog = "ttv")
public class Dag implements java.io.Serializable, DagInterface, Item {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String team;
	private String opmerkingen;
	private Date datum;
	private Set<Open> opens = new HashSet<Open>(0);
	private Set<Dienst> diensts = new HashSet<Dienst>(0);

	public Dag() {
	}

	public Dag(String team, String opmerkingen, Date datum) {
		this.team = team;
		this.opmerkingen = opmerkingen;
		this.datum = datum;
	}

	public Dag(String team, String opmerkingen, Date datum, Set<Open> opens,
			Set<Dienst> diensts) {
		this.team = team;
		this.opmerkingen = opmerkingen;
		this.datum = datum;
		this.opens = opens;
		this.diensts = diensts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "team", nullable = false)
	public String getTeam() {
		return this.team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	@Column(name = "opmerkingen", nullable = false, length = 65535)
	public String getOpmerkingen() {
		return this.opmerkingen;
	}

	public void setOpmerkingen(String opmerkingen) {
		this.opmerkingen = opmerkingen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datum", nullable = false, length = 10)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dag")
	public Set<Open> getOpens() {
		return this.opens;
	}

	public void setOpens(Set<Open> opens) {
		this.opens = opens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dag")
	public Set<Dienst> getDiensts() {
		return this.diensts;
	}

	public void setDiensts(Set<Dienst> diensts) {
		this.diensts = diensts;
	}

}
