package nl.ttva66;

// Generated 22-jun-2013 16:02:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;



/**
 * Zaaldienst generated by hbm2java
 */
@Entity
@Table(name = "zaaldienst", catalog = "ttv", uniqueConstraints = @UniqueConstraint(columnNames = "naam"))
public class Zaaldienst implements java.io.Serializable, ZaalDienstInterface, Item {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String naam;
	private String email;
	private int aantal;
	private boolean maandag;
	private boolean dinsdag;
	private boolean woensdag;
	private boolean donderdag;
	private boolean vrijdag;
	private boolean zaterdag;
	private boolean zondag;
	private String password;
	private boolean canlogin;
	private Set<Dienst> diensts = new HashSet<Dienst>(0);

	public Zaaldienst() {
	}

	public Zaaldienst(String naam, String email, int aantal, boolean maandag,
			boolean dinsdag, boolean woensdag, boolean donderdag,
			boolean vrijdag, boolean zaterdag, boolean zondag, String password,
			boolean canlogin) {
		this.naam = naam;
		this.email = email;
		this.aantal = aantal;
		this.maandag = maandag;
		this.dinsdag = dinsdag;
		this.woensdag = woensdag;
		this.donderdag = donderdag;
		this.vrijdag = vrijdag;
		this.zaterdag = zaterdag;
		this.zondag = zondag;
		this.password = password;
		this.canlogin = canlogin;
	}

	public Zaaldienst(String naam, String email, int aantal, boolean maandag,
			boolean dinsdag, boolean woensdag, boolean donderdag,
			boolean vrijdag, boolean zaterdag, boolean zondag, String password,
			boolean canlogin, Set<Dienst> diensts) {
		this.naam = naam;
		this.email = email;
		this.aantal = aantal;
		this.maandag = maandag;
		this.dinsdag = dinsdag;
		this.woensdag = woensdag;
		this.donderdag = donderdag;
		this.vrijdag = vrijdag;
		this.zaterdag = zaterdag;
		this.zondag = zondag;
		this.password = password;
		this.canlogin = canlogin;
		this.diensts = diensts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "naam", unique = true, nullable = false)
	public String getNaam() {
		return this.naam;
	}

	public void setNaam(String naam) {
		this.naam = naam;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "aantal", nullable = false)
	public int getAantal() {
		return this.aantal;
	}

	public void setAantal(int aantal) {
		this.aantal = aantal;
	}

	@Column(name = "maandag", nullable = false)
	public boolean isMaandag() {
		return this.maandag;
	}

	public void setMaandag(boolean maandag) {
		this.maandag = maandag;
	}

	@Column(name = "dinsdag", nullable = false)
	public boolean isDinsdag() {
		return this.dinsdag;
	}

	public void setDinsdag(boolean dinsdag) {
		this.dinsdag = dinsdag;
	}

	@Column(name = "woensdag", nullable = false)
	public boolean isWoensdag() {
		return this.woensdag;
	}

	public void setWoensdag(boolean woensdag) {
		this.woensdag = woensdag;
	}

	@Column(name = "donderdag", nullable = false)
	public boolean isDonderdag() {
		return this.donderdag;
	}

	public void setDonderdag(boolean donderdag) {
		this.donderdag = donderdag;
	}

	@Column(name = "vrijdag", nullable = false)
	public boolean isVrijdag() {
		return this.vrijdag;
	}

	public void setVrijdag(boolean vrijdag) {
		this.vrijdag = vrijdag;
	}

	@Column(name = "zaterdag", nullable = false)
	public boolean isZaterdag() {
		return this.zaterdag;
	}

	public void setZaterdag(boolean zaterdag) {
		this.zaterdag = zaterdag;
	}

	@Column(name = "zondag", nullable = false)
	public boolean isZondag() {
		return this.zondag;
	}

	public void setZondag(boolean zondag) {
		this.zondag = zondag;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "canlogin", nullable = false)
	public boolean isCanlogin() {
		return this.canlogin;
	}

	public void setCanlogin(boolean canlogin) {
		this.canlogin = canlogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zaaldienst")
	public Set<Dienst> getDiensts() {
		return this.diensts;
	}

	public void setDiensts(Set<Dienst> diensts) {
		this.diensts = diensts;
	}

}
